version: '3.8'

services:
  product-service:
    image: product-service:latest
    build: .
    container_name: product-service
    ports:
      - "82:82"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/$DB_NAME
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-root}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-root}
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres-db:5432/$DB_NAME
      SPRING_FLYWAY_USER: ${DB_USER:-root}
      SPRING_FLYWAY_PASSWORD: ${DB_PASSWORD:-root}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL:-http://eureka-server:8761/eureka}
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - postgres-db
    networks:
      - app-network

  postgres-db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_DB: $DB_NAME
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
