spring:
  application:
    name: ${APP_NAME}
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    baselineOnMigrate: true

server:
  port: ${SERVER_PORT}

management:
  server:
    port: 0

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true